compiler:
  solc:
    version: 0.8.20
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.2/contracts"
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1/contracts/src/v0.8/'
dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.2
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
