compiler:
  solc:
    version: 0.8.19
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.0-rc.0/contracts"
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1/contracts/src/v0.8/'
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.0-rc.0
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
