name: Brownie

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

jobs:
  brownie-test:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Brownie dependencies
        id: cache-brownie-packages
        uses: actions/cache@v3
        with:
          path: ~/.brownie/packages
          key: brownie-packages
      - name: Cache solc
        id: cache-solc
        uses: actions/cache@v3
        with:
          path: ~/.solcx
          key: solcx
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          yarn global add ganache-cli
          pip install eth-brownie
      - name: brownie-compile
        run: |
          brownie compile
      - name: brownie-test
        run: |
          brownie test
      - uses: actions/upload-artifact@v3
        with:
          name: interfaces-abi
          path: build/interfaces
      - uses: actions/upload-artifact@v3
        with:
          name: contracts-abi
          path: build/contracts
